/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SobreMiRouteImport } from './routes/sobre-mi'
import { Route as ServiciosRouteImport } from './routes/servicios'
import { Route as PsicoterapiaRouteImport } from './routes/psicoterapia'
import { Route as IndexRouteImport } from './routes/index'

const SobreMiRoute = SobreMiRouteImport.update({
  id: '/sobre-mi',
  path: '/sobre-mi',
  getParentRoute: () => rootRouteImport,
} as any)
const ServiciosRoute = ServiciosRouteImport.update({
  id: '/servicios',
  path: '/servicios',
  getParentRoute: () => rootRouteImport,
} as any)
const PsicoterapiaRoute = PsicoterapiaRouteImport.update({
  id: '/psicoterapia',
  path: '/psicoterapia',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/psicoterapia': typeof PsicoterapiaRoute
  '/servicios': typeof ServiciosRoute
  '/sobre-mi': typeof SobreMiRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/psicoterapia': typeof PsicoterapiaRoute
  '/servicios': typeof ServiciosRoute
  '/sobre-mi': typeof SobreMiRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/psicoterapia': typeof PsicoterapiaRoute
  '/servicios': typeof ServiciosRoute
  '/sobre-mi': typeof SobreMiRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/psicoterapia' | '/servicios' | '/sobre-mi'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/psicoterapia' | '/servicios' | '/sobre-mi'
  id: '__root__' | '/' | '/psicoterapia' | '/servicios' | '/sobre-mi'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PsicoterapiaRoute: typeof PsicoterapiaRoute
  ServiciosRoute: typeof ServiciosRoute
  SobreMiRoute: typeof SobreMiRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sobre-mi': {
      id: '/sobre-mi'
      path: '/sobre-mi'
      fullPath: '/sobre-mi'
      preLoaderRoute: typeof SobreMiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/servicios': {
      id: '/servicios'
      path: '/servicios'
      fullPath: '/servicios'
      preLoaderRoute: typeof ServiciosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/psicoterapia': {
      id: '/psicoterapia'
      path: '/psicoterapia'
      fullPath: '/psicoterapia'
      preLoaderRoute: typeof PsicoterapiaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PsicoterapiaRoute: PsicoterapiaRoute,
  ServiciosRoute: ServiciosRoute,
  SobreMiRoute: SobreMiRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
